#!/bin/bash
#PBS -N XXNAMEXX
#PBS -P e14
#PBS -l ncpus=1
#PBS -l mem=5GB
#PBS -l walltime=00:30:00
#PBS -l wd
#PBS -l software=matlab_unsw
#PBS -l storage=gdata/hh5+scratch/e14+gdata/e14+gdata/p66
#PBS -q express
#PBS -m e

module load matlab
module load matlab_licence/unsw

matlab -nodisplay -nodesktop -nosplash -r "fname='XXFNAMEXX';oname='XXONAMEXX';msk='XXMSKXX';Process_ACCESS_CM2;exit;"

