#!/bin/bash
#PBS -N CM2a
#PBS -P e14
#PBS -l ncpus=1
#PBS -l mem=8GB
#PBS -l walltime=06:00:00
#PBS -l wd
#PBS -l software=matlab_unsw
#PBS -l storage=gdata/hh5+gdata/ik11+scratch/e14+gdata/ua8+gdata/e14+gdata/p66
#PBS -q express
#PBS -M ryan.holmes@unsw.edu.au
#PBS -m e

module load matlab
module load matlab_licence/unsw

matlab -nodisplay -nodesktop -nosplash -r "ACCESS_SpecificHeat;exit;"

